// ---------------------------------------------------------------------------
// @todome/db – public API
// ---------------------------------------------------------------------------

// Types & constants
export type {
  TiptapDocument,
  TiptapNode,
  TiptapMark,
  TodoPriority,
  TodoStatus,
  ParentType,
  RemindRepeat,
  Result,
  Note,
  NoteSummary,
  Folder,
  Subtask,
  Todo,
  TodoList,
  CalendarEvent,
  Attachment,
  CreateNoteInput,
  UpdateNoteInput,
  CreateFolderInput,
  UpdateFolderInput,
  CreateTodoInput,
  UpdateTodoInput,
  CreateTodoListInput,
  UpdateTodoListInput,
  CreateCalendarEventInput,
  UpdateCalendarEventInput,
  CalendarProvider,
  CalendarSubscription,
  CreateCalendarSubscriptionInput,
  UpdateCalendarSubscriptionInput,
  ExternalCalendarEvent,
  DisplayEvent,
  MemberStatus,
  SharedCalendar,
  SharedCalendarMember,
  SharedCalendarEvent,
  Diary,
  DiaryMood,
  DiaryWeather,
  DiaryRating,
  CreateDiaryInput,
  UpdateDiaryInput,
  CreateAttachmentInput,
} from './types';

export {
  TODO_PRIORITIES,
  TODO_STATUSES,
  PARENT_TYPES,
  REMIND_REPEATS,
  CALENDAR_PROVIDERS,
  MEMBER_STATUSES,
  DIARY_MOODS,
  DIARY_WEATHERS,
  DIARY_RATINGS,
  Ok,
  Err,
} from './types';

// Supabase
export { supabase } from './supabase';
export type { Database } from './supabase';

// Repository layer
export {
  loadNotes,
  loadNoteSummaries,
  loadNoteById,
  createNote,
  updateNote,
  deleteNote,
  loadFolders,
  createFolder,
  updateFolder,
  deleteFolder,
  loadTodoLists,
  createTodoList,
  updateTodoList,
  deleteTodoList,
  loadTodos,
  createTodo,
  updateTodo,
  deleteTodo,
  batchUpdateTodos,
  loadCalendarEvents,
  createCalendarEvent,
  updateCalendarEvent,
  deleteCalendarEvent,
  loadDiaries,
  createDiary,
  updateDiary,
  deleteDiary,
  loadCalendarSubscriptions,
  createCalendarSubscription,
  updateCalendarSubscription,
  deleteCalendarSubscription,
  loadSharedCalendars,
  createSharedCalendar,
  updateSharedCalendar,
  deleteSharedCalendar,
  loadSharedCalendarMembers,
  loadAllSharedCalendarMembers,
  getMemberDisplayNames,
  createInviteToken,
  claimInvite,
  removeSharedCalendarMember,
  updateMemberVisibility,
  loadSharedCalendarEvents,
  createSharedCalendarEvent,
  updateSharedCalendarEvent,
  deleteSharedCalendarEvent,
} from './repository';
